import React from "react";

export default function head() {
  return (
    <>
      <title>Full Stack Developer based in Somalia</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
